package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C3044e;
import com.google.android.gms.common.api.C3044e.C3045a;
import com.google.android.gms.common.api.C3049h;
import com.google.android.gms.common.api.C3050i;
import com.google.android.gms.common.api.Status;
import java.util.concurrent.TimeUnit;

/* renamed from: com.google.android.gms.common.api.internal.bm */
public final class C3094bm<R extends C3049h> extends C3044e<R> {

    /* renamed from: a */
    private final Status f10730a;

    /* renamed from: a */
    public final R mo10866a(long j, TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo10867a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo10868a(C3045a aVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: a */
    public final void mo10869a(C3050i<? super R> iVar) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: b */
    public final boolean mo10870b() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* renamed from: c */
    public final Integer mo10871c() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* access modifiers changed from: 0000 */
    /* renamed from: d */
    public final Status mo10961d() {
        return this.f10730a;
    }
}
